<?php namespace View; Use _; ?>
<?//$T->render('box')?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <title>neunzehn83</title>
    
    <link rel="stylesheet" href="<?=url('css/reset.css')?>" media="screen,projection" />
    <link rel="stylesheet" href="<?=url('css/style.css')?>" media="screen,projection" />
    <link rel="shortcut icon" href="favicon.ico" />    
    
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <!--[if lt IE 9]>
        <script src="js/ie.js"></script> 
        <link rel="stylesheet" href="css/ie.css" media="screen,projection" />        
    <![endif]-->   
</head>
<body>
    <header>
        <h1><a href="<?=url('/')?>">neunzehn83.de</a></h1>
        <nav>
            <ul>
                <li>Features</li>
                <li>Blog</li>
                <?php if (_::Auth()->getId()) { ?> 
                <li><a href="<?=url('account')?>">Account (<?=_::Auth()->user['name']?>)</a></li>
                <?php if (_::ACL()->check('admin')) { ?>
                <li><a href="<?=url('admin/index')?>"><strong>Admin</strong></a></li>
                <?php } ?>
                <li><a href="<?=url('account/logoff', null, array('token' => $token))?>">Logout</a></li>
                <?php } else { ?> 
                <li><a href="<?=url('signup')?>">Signup</a></li>
                <li><a href="<?=url('login')?>">Login</a></li>
                <?php } ?> 
            </ul>
        </nav>
    </header>
    
    <div id="wrapper">
        <?$T->render()?>
    </div><!-- wrapper -->
    
    <footer>
        <p>
            &copy; <?=date('Y')?> neunzehn83.de, powered by lmsbe       
        </p>
    </footer>

</body>
</html>
