<?php namespace View; Use _; ?>
        <h1>Seiten</h1>
        <ul>
            <li><a href="<?=url('about')?>">About me</a></li>
            <li><a href="<?=url('archiv')?>">Archiv</a></li>
        </ul>

        <h1>Interessantes</h1>
        <ul>
<?php foreach ($featured as $post) { ?>
            <li><a href="<?=url($post['link'])?>"><?=$post['title']?></a></li>
<?php } ?>

        </ul>

        <h1>Neue Beiträge</h1>
        <ul>
<?php foreach ($newest as $post) { ?>
            <li><a href="<?=url($post['link'])?>"><?=$post['title']?></a></li>
<?php } ?>

        </ul>

        <h1>Kategorien</h1>
        <ul>
<?php foreach ($cats as $cat) { ?>
            <li><a href="<?=url(\Model\Builder::makeUri($cat))?>"><?=$cat?></a></li>
<?php } ?>

        </ul>

        <h1>Blogroll</h1>
        <ul>
            <li><a href="http://blog.kevin-k.com/">kevin's blog</a></li>
        </ul>