        <h1>Seiten</h1>
        <ul>
            <li><a href="">About me</a></li>
            <li><a href="">Archiv</a></li>
        </ul>

        <h1>Interessantes</h1>
        <ul>
            <li><a href="">About me</a></li>
            <li><a href="">Archiv</a></li>
        </ul>

        <h1>Neue Beiträge</h1>
        <ul>
            <li><a href="">About me</a></li>
            <li><a href="">Archiv</a></li>
        </ul>

        <h1>Kategorien</h1>
        <ul>
            <li><a href="">About me</a></li>
            <li><a href="">Archiv</a></li>
        </ul>

        <h1>Blogroll</h1>
        <ul>
            <li><a href="">About me</a></li>
            <li><a href="">Archiv</a></li>
        </ul>