<?php namespace View; Use _; ?>
<?//$T->render('box')?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <title>No nix narrets! - neunzehn83.de</title>
    
    <link rel="stylesheet" href="<?=url('css/reset.css')?>" media="screen,projection" />
    <link rel="stylesheet" href="<?=url('css/style.css')?>" media="screen,projection" />
    <link rel="shortcut icon" href="favicon.ico" />    

    <meta name="description" content="" />

    <!--[if lt IE 9]>
        <script src="js/ie.js"></script> 
        <link rel="stylesheet" href="css/ie.css" media="screen,projection" />        
    <![endif]-->   
</head>
<body>
    <header>
        <h1><a href="<?=url('/')?>">neunzehn83.de</a></h1>
        <h2>Ein Mann, ein Blog, kein Plan.</h2>
        <nav>
            <ul>
                <li><a href="<?=url('account')?>">Github</a></li>
                <li><a href="<?=url('account')?>">Twitter</a></li>
                <li><a href="<?=url('about')?>">About me</a></li>
            </ul>
        </nav>
    </header>    
    
    <div>
<?$T->render()?>        
    </div>    
    
    <aside>
<?$T->render('sidebar')?>
    </aside>

    <footer>
        <p><small>&copy;</small> <?=date('Y')?> neunzehn83.de, powered by lmsbe | <a href="#">RSS</a></p>
    </footer>
</body>
</html> 
